### ISSUE TITLE
1 day or 2 days worth of material?

### ISSUE THREAD

**Issue by jcoliver** [datacarpentry/socialsci-workshop#21]
The home page for the Social Sciences Data Carpentry says the curriculum is designed for two days of instruction. However the schedule of Data + OpenRefine + R seems to only take one day - are the lesson time estimates accurate?

**Comment by ErinBecker** [comment]
@jcoliver - I just taught this last week. The time estimates are not accurate. It was two full days of material. The R lesson took about a day and a half. I've put in some issues, including for updating timing, so this should be updated soon.
