### ISSUE TITLE
describe data

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/socialsci-workshop#3]
The index.md page has a place for introducing the data that will be used in this workshop, but it is currently empty. @PeterSmyth12 could you please add a short description of the source of the data, similar to how the data is introduced for the genomics workshop [here](http://www.datacarpentry.org/genomics-workshop/)?

**Comment by PeterSmyth12** [comment]
A description of the two data sets used has been added with links to the setup page from where they can be downloaded.

**Comment by fmichonneau** [comment]
@PeterSmyth12  it's a good start, but more information is needed about the dataset. These lessons will be taught by instructors who are not familiar with the SAFI dataset, so it needs to be made very clear to them what this dataset is describing: see https://github.com/datacarpentry/spreadsheets-socialsci/issues/44 for suggestions of the type of questions the description should answer.
