### ISSUE TITLE
Include a sample schedule for workshops

### ISSUE THREAD

**Issue by bencomp** [datacarpentry/socialsci-workshop#55]
This general suggestions follows up from a conversation on #33, which appears to be outdated. It still seems like a good idea to have sample schedule, even if the suggestion in #33 cannot be included at this time for technical reasons.

Currently the "Schedule" section on the workshop page is empty, because it is generated by the [Carpentries theme][theme] within <https://github.com/carpentries/carpentries-theme/blob/main/_includes/syllabus.html> and there are no episodes in this pseudo-lesson that would fill the schedule. It looks "broken".

Although I have write access to this repository, I don't feel I have a good solution to offer.
If we resolved the merge conflict(s) in the existing #33 and perhaps update the suggested timings in that schedule, we would still have the empty generated schedule.
Alternatively, if we added pseudo-episodes to the pseudo-lesson, that would probably show up nicely, but mean more work.
Yet another potential solution could be to use a different template so that the schedule would not be generated. But then it could make sense to try to migrate to The Workbench – and I believe at some point pseudo-lessons like this one will be migrated (maybe to a different system than the Workbench).

[theme]: https://github.com/carpentries/carpentries-theme

**Comment by tobyhodges** [comment]
> Although your PR did not add a schedule (as per the issue title)

Guilty as charged - sorry! 🙃 

If you would like to add a schedule, [the Genomics Workshop overview site](https://datacarpentry.org/genomics-workshop/) has a nice example of how that could look. Since #57 was merged a _Schedule_ section can now be added as Markdown within the main content of `index.md`.
